"""initial schema

Revision ID: 23556375cc0d
Revises:
Create Date: 2026-08-27 08:44:09.690110+00:00

Adopts an existing database as well as creating a fresh one.

Every database that already exists was created by
`SQLModel.metadata.create_all()` at startup and has no `alembic_version`
table. Running a plain autogenerated revision against one of those fails on
the first `CREATE TABLE`, which is exactly the moment somebody reaches for
`--force` or deletes the volume. So each table is created only when it is
absent, and the revision is safe to run against:

*   a fresh, empty database — every table is created;
*   a database from before the `jobs` table existed — `jobs` is created and
    the six older tables are left alone, rows intact;
*   a database already at head — nothing happens.

Nothing here drops or rewrites a table that already exists. If a pre-existing
table has a *different* shape than this revision describes, that is a
divergence a person must look at, and `scripts/check_migrations.py` reports
it rather than this file silently reconciling it.

`downgrade` drops everything, which for the initial revision means deleting
every run report, draft and profile. It exists so the revision is complete
and so migration tests can round-trip; it is not a rollback procedure. The
rollback procedure is restoring a backup — see `docs/runbooks.md`.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import context, op

revision: str = "23556375cc0d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _existing_tables() -> set[str]:
    """What is already in the database, or nothing in offline mode.

    `--sql` has no connection to inspect — it renders the migration for a
    reviewer, and the thing worth reviewing is the full CREATE TABLE set. So
    offline mode reports an empty database and emits everything.
    """
    if context.is_offline_mode():
        return set()
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    """Create the initial schema.

    This is the adoption point for databases created by `create_all()` before
    migrations existed: every statement is written to be safe against tables
    that are already there, so stamping an existing database and upgrading it
    does not drop anything.
    """
    existing = _existing_tables()

    if "answers" not in existing:
        op.create_table(
            "answers",
            sa.Column("answer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("founder_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column(
                "question_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("payload", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("answer_id"),
        )
        with op.batch_alter_table("answers", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_answers_founder_id"), ["founder_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_answers_question_key"), ["question_key"], unique=False
            )

    if "drafts" not in existing:
        op.create_table(
            "drafts",
            sa.Column("draft_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("founder_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column(
                "opportunity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column("payload", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("draft_id"),
        )
        with op.batch_alter_table("drafts", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_drafts_founder_id"), ["founder_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_drafts_opportunity_id"),
                ["opportunity_id"],
                unique=False,
            )

    if "inbox" not in existing:
        op.create_table(
            "inbox",
            sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column(
                "idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column("founder_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column(
                "opportunity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("payload", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("item_id"),
        )
        with op.batch_alter_table("inbox", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_inbox_created_at"), ["created_at"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_inbox_founder_id"), ["founder_id"], unique=False
            )
            # Unique: never notify twice about the same opportunity. Enforced
            # by the database, not by a check-then-act in Python.
            batch_op.create_index(
                batch_op.f("ix_inbox_idempotency_key"),
                ["idempotency_key"],
                unique=True,
            )
            batch_op.create_index(
                batch_op.f("ix_inbox_opportunity_id"), ["opportunity_id"], unique=False
            )

    if "jobs" not in existing:
        op.create_table(
            "jobs",
            sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("founder_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column(
                "idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            ),
            sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("payload", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("job_id"),
        )
        with op.batch_alter_table("jobs", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_jobs_created_at"), ["created_at"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_jobs_founder_id"), ["founder_id"], unique=False
            )
            # Unique: a scheduler retry resolves to the original job rather
            # than starting a second run.
            batch_op.create_index(
                batch_op.f("ix_jobs_idempotency_key"),
                ["idempotency_key"],
                unique=True,
            )
            batch_op.create_index(
                batch_op.f("ix_jobs_status"), ["status"], unique=False
            )

    if "opportunities" not in existing:
        op.create_table(
            "opportunities",
            sa.Column(
                "opportunity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("first_seen_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("payload", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("opportunity_id"),
        )
        with op.batch_alter_table("opportunities", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_opportunities_source"), ["source"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_opportunities_updated_at"), ["updated_at"], unique=False
            )

    if "profiles" not in existing:
        op.create_table(
            "profiles",
            sa.Column("founder_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("payload", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("founder_id"),
        )

    if "runs" not in existing:
        op.create_table(
            "runs",
            sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("founder_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("started_at", sa.DateTime(), nullable=False),
            sa.Column("payload", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("run_id"),
        )
        with op.batch_alter_table("runs", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_runs_founder_id"), ["founder_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_runs_started_at"), ["started_at"], unique=False
            )


def downgrade() -> None:
    """Drops every table. This deletes every run report, draft and profile.

    Present so the revision is complete and round-trippable in tests. It is
    not the rollback procedure — rolling back a deployment restores a backup
    (docs/runbooks.md). Reaching for this on a database that matters is how
    an audit trail stops existing.
    """
    for table in (
        "runs",
        "profiles",
        "opportunities",
        "jobs",
        "inbox",
        "drafts",
        "answers",
    ):
        op.drop_table(table)
